[metadata]
name = audiopy
version = 0.1.0
author = Adarsh Kotawar
description = Open-source framework for intelligent audio editing
long_description = file: README.md
long_description_content_type = text/markdown
license = MIT
license_files = LICENSE

[options]
packages = find:
install_requires =
    librosa
    numpy
    scipy
    soundfile
    transformers
    torch
    torchaudio

python_requires = >=3.8

[options.packages.find]
exclude =
    tests
    examples